//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDemo.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenti
    {
        public int IdStudente { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascita { get; set; }
        public Nullable<int> idCorso { get; set; }
    
        public virtual Corsi Corsi { get; set; }
    }
}
